### ISSUE TITLE
No Webnar que assisti aparecia um APP Simples Nacional

### ISSUE THREAD

**Issue by eduardotd** [Trust-Code/Tutorial-Instalacao#2]
Em primeiro lugar parabéns pelo impressionante trabalho de localização do ODOO 10.

Ficou realmente excelente...

Rodei o script do tutorial numa nova instalação UBUNTU 14.04.

Aparentemente tudo OK. Habilitei as opções de desenvolvedor e consegui instalar os recursos para emissão de NF.

A única coisa que não achei foi o app de configuração Simples Nacional que aparece no Webnar...

Alguém sabe qual repositório adicional preciso baixar...

Um link para um passo a passo para configurar a Posição Fiscal também ajudaria muito...

Muito obrigado!

**Comment by danimaribeiro** [comment]
Obrigado.

O módulo de simples nacional foi removido, se você instalou o br_nfe já tem tudo que precisa para emitir notas do simples.

Quanto a posição fiscal vamos fazer sim, ainda estamos efetuando melhorias nela.

**Comment by eduardotd** [comment]
Obrigado novamente!
