### ISSUE TITLE
Problemas na instalação em máquina de desenvolvimento.

### ISSUE THREAD

**Issue by guilhermependezza** [Trust-Code/Tutorial-Instalacao#6]
Instalei um Ubuntu 16.04.1 LTS, e segui o tutorial de instalação do sistema. Porém houve erro na instalação do pillow ( pip install pillow ). O erro diz que não é possível a compilação do pacote.

Solução: instalar o pacote python-dev
sudo apt-get install python-dev

**Comment by ducaw** [comment]
Obrigado pela dica Guilherme, tinha travado nessa parte na minha maquina (ubuntu 16.04.02).

Além disso, depois ocorreu um erro por falta do pacote gcc, então instalei: `sudo apt-get install gcc`

Depois disso a instalação ocorreu bem.

**Comment by MACROSANN** [comment]
alguém pode ajudar com esse erro?

joao_santana@ubuntu-xenial-1:~$ sudo pip install --upgrade pip
The directory '/home/joao_santana/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/joao_santana/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
joao_santana@ubuntu-xenial-1:~$ 

acho que não está atualizando para o python 3

Agradeço
